name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build_for_ghidra:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghidra:  ["10.4"]

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
  
    - name: Install Java
      uses: actions/setup-java@v1
      with:
        java-version: "17"
        java-package: jdk
        architecture: x64

    - name: Install Ghidra ${{ matrix.version }}
      uses: er28-0652/setup-ghidra@master
      with:
        version: ${{ matrix.ghidra }}

    - name: Build the extension for Ghidra ${{ matrix.version }}
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.3
        arguments: -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
